/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bancodigital;

import bancodigital.models.*;

public class App {
    public static void main(String[] args) {
        Pessoa p1 = new PessoaFisica("Marcos", "23/09/2001", "123213123");
        System.out.println(p1);
    }
}
